# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0004_auto_20171011_1717'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='duration_seconds',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='latitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='longitude',
            field=models.DecimalField(decimal_places=7, max_digits=10),
        ),
    ]
