# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 21:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0007_auto_20171011_2136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='duration_seconds',
            field=models.FloatField(),
        ),
    ]
