# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-11 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0008_auto_20171011_2150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='shape',
            field=models.CharField(db_index=True, max_length=512),
        ),
    ]
