# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-14 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0010_auto_20171011_2237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sighting',
            name='latitude',
            field=models.DecimalField(db_index=True, decimal_places=7, max_digits=10),
        ),
        migrations.AlterField(
            model_name='sighting',
            name='longitude',
            field=models.DecimalField(db_index=True, decimal_places=7, max_digits=10),
        ),
    ]
